{{- if .Values.onehouseConfig.imagePullSecrets.accessToken }}
{{- /* Hardcoded image pull secret configuration */ -}}
{{- $secretName := "onehouse-docker-registry-secret" }}
{{- $username := "onehouseai" }}
{{- $registry := "https://index.docker.io/v1/" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quanton-spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-pull-secret
data:
  .dockerconfigjson: {{ template "image-pull-secret.dockerconfigjson" . }}
{{- end }}

{{- define "image-pull-secret.dockerconfigjson" }}
{{- /* Docker registry configuration for both Docker Hub and dist.onehouse.ai */ -}}
{{- $registry1 := "https://index.docker.io/v1/" }}
{{- $registry2 := "https://dist.onehouse.ai" }}
{{- $username := "onehouseai" }}
{{- $password := .Values.onehouseConfig.imagePullSecrets.accessToken }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $entry := printf "\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"" $username $password $auth }}
{{- $dockerconfigjson := printf "{\"auths\":{\"%s\":{%s},\"%s\":{%s}}}" $registry1 $entry $registry2 $entry }}
{{- $dockerconfigjson | b64enc }}
{{- end }}
