{{- if and .Values.monitoring .Values.monitoring.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quanton-spark.fullname" . }}-monitoring-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quanton-spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring-watcher
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quanton-spark.fullname" . }}-monitoring-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quanton-spark.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring-watcher
subjects:
  - kind: ServiceAccount
    name: {{ include "quanton-spark.fullname" . }}-{{ .Values.monitoring.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "quanton-spark.fullname" . }}-monitoring-watcher
  apiGroup: rbac.authorization.k8s.io
{{- end }}
