{{- if and .Values.onehouseConfig .Values.onehouseConfig.mtls .Values.onehouseConfig.mtls.clientCert .Values.onehouseConfig.mtls.clientKey }}
apiVersion: v1
kind: Secret
metadata:
  name: mutual-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: quanton-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  client-cert.pem: {{ .Values.onehouseConfig.mtls.clientCert | b64enc | quote }}
  client-key.pem: {{ .Values.onehouseConfig.mtls.clientKey | b64enc | quote }}
{{- end }}
