{{- if .Values.onehouseConfig.quantonOperatorPublicCert }}
apiVersion: v1
kind: Secret
metadata:
  name: quanton-operator-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: quanton-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: quanton-operator
type: Opaque
data:
  public-cert.pem: {{ .Values.onehouseConfig.quantonOperatorPublicCert | b64enc | quote }}
{{- end }}
