{{- if and .Values.onehouseConfig .Values.onehouseConfig.quantonOperatorCACert }}
apiVersion: v1
kind: Secret
metadata:
  name: quanton-operator-ca-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  ca-cert.pem: {{ .Values.onehouseConfig.quantonOperatorCACert | b64enc | quote }}
{{- end }}
