apiVersion: v1
kind: ConfigMap
metadata:
  name: quanton-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: controller
data:
  config.json: |
    {
      "quantonSparkImage": {{ .Values.onehouseConfig.quantonSparkImage | quote }},
      "appsNamespace": {{ if .Values.quantonOperator.jobNamespaces }}{{ .Values.quantonOperator.jobNamespaces | join "," | quote }}{{ else }}""{{ end }},
      "otelServiceName": "quanton-operator",
      "onehouseProjectId": {{ .Values.onehouseConfig.projectId | quote }},
      "onehouseLinkId": {{ .Values.onehouseConfig.linkId | quote }},
      "onehouseEnvironment": {{ .Values.onehouseConfig.environment | quote }},
      "onehouseCloudProvider": {{ .Values.onehouseConfig.cloudProvider | quote }},
      "additionalSparkParamsToMask": {{ .Values.quantonOperator.additionalSparkParamsToMask | toJson }},
      "gwcEndpoint": {{ .Values.onehouseConfig.endpoint | quote }},
      "metricsEndpoint": {{ .Values.onehouseConfig.metricsEndpoint | quote }},
      "mtlsCertPath": "/etc/mutual-tls/client-cert.pem",
      "mtlsKeyPath": "/etc/mutual-tls/client-key.pem"
    }
