apiVersion: v1
kind: ConfigMap
metadata:
  name: quanton-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: controller
data:
  config.json: |
    {
      "quantonSparkImage": {{ .Values.onehouseConfig.quantonSparkImage | quote }},
      "appsNamespace": {{ if .Values.quantonOperator.jobNamespaces }}{{ .Values.quantonOperator.jobNamespaces | join "," | quote }}{{ else }}""{{ end }},
      "otelServiceName": "quanton-operator",
      "additionalSparkParamsToMask": {{ .Values.quantonOperator.additionalSparkParamsToMask | toJson }},
      "mtlsCertPath": "/etc/mtls/client-cert.pem",
      "mtlsKeyPath": "/etc/mtls/client-key.pem",
      "helmChartVersion": {{ .Chart.Version | quote }}
    }
