{{- if and .Values.onehouseConfig .Values.onehouseConfig.quantonOperatorPublicCert }}
apiVersion: v1
kind: Secret
metadata:
  name: quanton-operator-public-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onehouse-quanton-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  public-cert.pem: {{ .Values.onehouseConfig.quantonOperatorPublicCert | b64enc | quote }}
{{- end }}
