apiVersion: quantonsparkoperator.onehouse.ai/v1beta2
kind: QuantonSparkApplication
metadata:
  name: quanton-spark-pi-java-example
  namespace: default
spec:
  sparkApplicationSpec:
    type: Java
    mode: cluster
    image: "dist.onehouse.ai/onehouseai/quanton-spark:quanton-operator-release-v0.2.0-al2023"
    imagePullPolicy: IfNotPresent
    mainClass: org.apache.spark.examples.JavaSparkPi
    mainApplicationFile: "local:///opt/spark/examples/jars/calculate-pi-example_2.12-3.5.0.jar" # TBD
    arguments:
      - "100"
    sparkVersion: "3.5.0"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "1024m"
      labels:
        version: "3.5.0"
      serviceAccount: spark-operator-spark
    executor:
      cores: 1
      instances: 2
      memory: "1024m"
      labels:
        version: "3.5.0"
